{
 "title": "InfiniBand Switches Status",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "InfiniBand Collector Scrape Status (Yes=OK, No=ERRORS)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    { "expr": "infiniband_collector_scrape_ok", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Count of Swtiches and PSUs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "count(infiniband_switches_status_fans)",
     "legendFormat": "Switches"
    },
    {
     "expr": "sum(count(infiniband_switches_status_power_supply_status) by (psu))",
     "legendFormat": "PSU"
    }
   ]
  },
  {
   "title": "Power Supply",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power Supply (Yes=OK, No=ERROR)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "targets": [
      {
       "expr": "infiniband_switches_status_power_supply_status",
       "legendFormat": "{{name}}-PSU{{psu}}"
      }
     ]
    },
    {
     "title": "Power Supply Fan (Yes=OK, No=ERROR)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "targets": [
      {
       "expr": "infiniband_switches_status_power_supply_fan",
       "legendFormat": "{{name}}-PSU{{psu}}"
      }
     ]
    },
    {
     "title": "Power Supply DC Status (Yes=OK, No=ERROR)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "targets": [
      {
       "expr": "infiniband_switches_status_power_supply_dc",
       "legendFormat": "{{name}}-PSU{{psu}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Fans",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fans Status (Yes=OK, No=ERROR)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "targets": [
      {
       "expr": "infiniband_switches_status_fans",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}